[IssuerHelper] make issuer helper contract compatible with ERC2771
Xfers/Orchid-PBM pull request #8
Opened 2023-05-09 19:43 UTC by jacobshan

as title.

2023-05-10 03:30 UTC, alcedo requested changes

2023-05-10 03:30 UTC, alcedo commented on PBMRC/PBMRC2/src/signer.js
> +  { name: 'to', type: 'address' },
how do you know that this is the data structure requred?

2023-05-10 03:30 UTC, alcedo commented on PBMRC/PBMRC2/test/IssuerHelper.test.js
> +        from: whitelister.address,
can you write a piece of test to ensure that `whitelister.address` balance is 0?

2023-05-10 03:30 UTC, alcedo commented on PBMRC/PBMRC2/test/IssuerHelper.test.js
> +    it("should transfer tokens from wallet to IssuerHelper and call loadAndSafeTransfer on PBMRC2", async function () {
we will align again on the new IPBMRC2

2023-05-10 03:32 UTC, alcedo commented
note that the title should adhere to the git commit formats which references the JIRA number

2023-05-10 04:00 UTC, jacobshan commented on PBMRC/PBMRC2/src/signer.js
> +  { name: 'to', type: 'address' },
it's in the MinimalForwarder contract.
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/4961a51cc736c7d4aa9bd2e11e4cbbaff73efee9/contracts/metatx/MinimalForwarder.sol#L15

2023-05-10 05:37 UTC, jacobshan commented on PBMRC/PBMRC2/contracts/Migrations.sol
> +
this is a truffle specific convention to manage smart contract deployment. mainly used to keep track of the last completed migration. so that can run necessary migrations only.

2023-05-10 08:54 UTC, jacobshan commented on PBMRC/PBMRC2/test/IssuerHelper.test.js
> +    it("should transfer tokens from wallet to IssuerHelper and call loadAndSafeTransfer on PBMRC2", async function () {
call loadTo and safeTransferFrom from the new IPBMRC2

2023-05-10 19:32 UTC, jacobshan commented on PBMRC/PBMRC2/test/IssuerHelper.test.js
> +
@alcedo above comment explains what would happen when forwarder underlying function call fails.

2023-05-10 19:35 UTC, jacobshan commented on PBMRC/PBMRC2/test/IssuerHelper.test.js
> +        from: whitelister.address,
added below!

2023-05-17 04:02 UTC, jacobshan commented
close for now. will split the contract and open a new PR

2023-05-17 04:02 UTC, closed without merging